# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ML Visual
tagline:          'A Jekyll theme'
description:      'The Machine Learning Visualized.'
baseurl:          "/ML-visual"

author:
  name:           'Kin'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kin-cs
